### PR TITLE
added snackbars

### PR DESCRIPTION
**Pull request by joshplumley**
Material ui does not support stackable snackbars out of the box. Its actually in a MR currently from an issue back in 2017!. MUI put a fight up due to the guidelines. Anyways, I ended up using notistack, so make sure you do a yarn install.

I added snackbars to all the api requests (not the GETs). I did not add them to the deletes on the dialog popups, since it seems we are going to remove that delete in favor of deleting all upon submitting the change set. 

I added the snackbars on the left bottom, so they would not stack and cover the pagination.

I can change styling and wording, just let me know!

### CODE REVIEW

**Comment by joshplumley** [comment]
@jarrilla should be good to go!

**Comment by jarrilla** [comment]
@joshplumley
This doesn't seem to be handling errors.

In particular, I'm looking at deleting a packing slip that exists in a shipment (which is forbidden and throws a 400 error).

Instead I'm seeing "Packing slip deleted" when it's not actually being deleted.

The styling is spot on, however; I like what you've done.

**Comment by joshplumley** [comment]
Hmm. I'll take a look. It was working before the merge. Perhaps I messed up
the conflict.

**Comment by joshplumley** [comment]
@jarrilla Im not able to reproduce what you are seeing. Im going to the shipments page, going to history, edit a shipment, delete a packing slip. I get a delete confirmation dialog. If I press OK (doesnt delete yet until I press OK on the edit shipment dialog) and then press OK of edit Shipment, the packing slip is deleted. 

Two questions
1) If a packing slip should never be deleted from a shipment, should we remove that trash bin icon from the edit dialog? 
2) I think the error snackbars are working fine, however; we are catching all errors in the `server.js` so the `catch` on all our api calls (the `then` `catch` statements) - are not being triggered. I think the solution here is to rethrow the errors being caught in the `server.js` file so that the exception can be handled. Also, It looks like we are using `alert` and using snackbars. Seems redundant. Should we remove the alerts?

**Comment by jarrilla** [comment]
We should definitely remove the alerts.

The delete workflow you're describing is ok. What isn't is if you try to
delete a packing slip (in the packing slip history) that has already been
shipped.

**Comment by joshplumley** [comment]
Ah, I see what you mean now.

Try it now. I did what I mentioned earlier. In addition, Im using the error from the response so the user has more of an idea of what went wrong. If you prefer the generic message, let me know

image

As a side note and most likely another issue, but in this specific scenario, it seems you are able to delete the packing slip through editing (deleting) all parts from packing slip. If it has already been shipped, Im guessing this should not be allowed. Let me know and I can make the issue.

**Comment by jarrilla** [comment]
Awesome!

**Pull request merged**
