### PR TITLE
Fulfilled check bug fix

### LINKED ISSUE #76: In packing slip queue, searching ignores "Show Fulfilled" check state
to replicate:
1) uncheck "show fulfilled batches" as to hide batches that have already been fulfilled
2) type something in the search filter, notice that fulfilled batches come back

### PR DESCRIPTION
**Pull request by joshplumley**
closes #76 

@jarrilla, this one was more involved than at first glance. Check this one out and make sure I covered it all.

The bug is fixed. I also added the last thing we chated about. So now, the checked row will take priority but when it is unchecked, it will be removed if other search criteria happen to filter that row out.

### CODE REVIEW

**Comment by joshplumley** [comment]
Ah feel free to check it out, but I found an issue.

**Comment by jarrilla** [comment]
I'll hold off until the mentioned issue is hashed out.

**Comment by joshplumley** [comment]
OK, there were a lot of little nuances with this one that were not immediately obvious, but I think I got it. Run this one through the ringer!

**Comment by jarrilla** [comment]
Hmm, for the most part this is GREAT!

However, there's a way to brick it...
1. Load "Queue"
2. Uncheck "Show Fulfilled Batches"
3. Click "History"
4. Click "Queue"

fulfilled batches will show up again

**Comment by joshplumley** [comment]
Ah good catch. I take a peek.

**Comment by joshplumley** [comment]
Ok I got it, but question for you. When you switch tabs like that, do you want the selection reset?

**Comment by jarrilla** [comment]
> Ok I got it, but question for you. When you switch tabs like that, do you want the selection reset?

Yes, I think that's fine as long as that behavior is consistent.

**Comment by jarrilla** [comment]
@joshplumley 
Found another one with switching tabs!

From queue:
1. Type anything on the Search filter (for example, something that makes everything go away "asdfasdfasdf")
2. Go to History, and back to Queue
3. Search input will be empty, and so will the table b/c of previous filter

In response to your question above,
I've just said that resetting selection & filters is probably the easiest and most consistent thing to do when switching tabs like that.

Open to a different opinion.

**Comment by joshplumley** [comment]
Yep, I knew that bug existed. I was just waiting for your response to fix since we could have reset it or hung on to the selection/searc/erc. Ill take a peek

**Pull request merged**
