### PR TITLE
Nav bar added for shipping, receiving, packing

### LINKED ISSUE #73: Mockup Nav bar
Options  - packing shipping receiving

1) Top
2) right

no need to make it work yet, just want to get a feel for layout

### PR DESCRIPTION
**Pull request by joshplumley**
image

@jarrilla Here is the top nav bar. We can work on styling text and whatnot. The navbar color will change (once all connected). It actually changes now if you used the buttons on the button right now if you want to see what it looks like. Im assuming those will go away in favor of the navigation bar. 

My opinion: I think I like this better than the drawer docked on the right (or left). It leaves more space for larger tables with more data. However, just let me know and ill move on a drawer on the right (or left) if you want. 

Once you signoff on the mockup, Ill connect all the dots in this branch.

closes #73

### CODE REVIEW

**Comment by jarrilla** [comment]
This actually looks much better than I was picturing in my head. What about moving the tabs to be aligned to the right instead so there's even less overlap with the parent nav menu.

**Comment by joshplumley** [comment]
If I'm understanding correctly, I would leave the tabs where they are, but along your line of thinking, I might move the BUTTON, SEARCH, and CHECKBOXES to the navbar towards the right, to save on space and have those options change dynamically (like they do now) when you click on a different tab.

**Comment by joshplumley** [comment]
Sure can:
image

**Comment by jarrilla** [comment]
Neat!

I'm having a look at https://mui.com/material-ui/react-tabs/
Could we use tabs instead of buttons so that it's easier to show what's selected (like the underline that is used in the examples)

**Comment by joshplumley** [comment]
@jarrilla  I did not. Sorry about that.

**Comment by joshplumley** [comment]
@jarrilla take this for a spin. I rebased with main before I noticed the target was changed to "addReceiving" branch. I cherry pick and rebase with the right branch if you want or we can merge this with main. Just let me know.

**Review by jarrilla — APPROVED** [review]

**Pull request merged**
