### PR TITLE
51 new shipment flow

### LINKED ISSUE #51: Implement new create shipment flow
When creating shipment for packing slips w/ destination !== CUSTOMER
a) If the shipping method is CARRIER add “Shipping Address”
b) Remove “Customer Account” fields from front-end; this does not apply to anything except customer shipments

### PR DESCRIPTION
**Pull request by jbolles94**
Closes #51

### CODE REVIEW

**Comment by jarrilla** [comment]
This is sweet!

Couple things
- Seems to be missing the "Shipping Address" portion when creating a Shipment that is being carrier shipped.
- When hitting the "back" button (in "Received by") it goes all the way back to the shipment-type selection instead of back 1 page to the shipping address input
- (this one is my fault) can we change the "cancel" button in the shipping input dialog for a "back" button instead.. this one *should* go back to page 1
- Can we make the carrier details dialog page a little bit wider (so it matches the customer one).. it feels a bit too narrow as is

The flow is otherwise, really solid!

**Comment by jbolles94** [comment]
> @jbolles94 This is sweet!
> 
> Couple things
> 
> * Seems to be missing the "Shipping Address" portion when creating a Shipment that is being carrier shipped.
> * When hitting the "back" button (in "Received by") it goes all the way back to the shipment-type selection instead of back 1 page to the shipping address input
> * (this one is my fault) can we change the "cancel" button in the shipping input dialog for a "back" button instead.. this one _should_ go back to page 1
> * Can we make the carrier details dialog page a little bit wider (so it matches the customer one).. it feels a bit too narrow as is
> 
> The flow is otherwise, really solid!

I couldn't reproduce the first bullet on a packing slip with the destination type VENDOR. If it is supposed to show when the destination is of type CUSTOMER too, I can alter that. I believe I have fixed the rest of the issues you brought up. Let me know if I misunderstood any!

**Comment by jarrilla** [comment]
Right on. I might've had junk data on my end.

I'm having the below issues when merging, however. could you merge addDestination into your branch and have a look?

Only thing that's annoying now is that clicking "back" from the last modal (i.e. tracking details) is resetting the shipping address that was already typed in there.

*edit* this seems to be only an issue with "Carrier" shipments.. where the shipping address field is not being set at all. For example, going through the entire process is not writing a shipping address at the end.

**Comment by jbolles94** [comment]
> Right on. I might've had junk data on my end.
> 
> I'm having the below issues when merging, however. could you merge addDestination into your branch and have a look?
> 
> Only thing that's annoying now is that clicking "back" from the last modal (i.e. tracking details) is resetting the shipping address that was already typed in there. (For the record, i checked it the other way around... merge 51 into addDestination)
> 
> _edit_ this seems to be only an issue with "Carrier" shipments.. where the shipping address field is not being set at all. For example, going through the entire process is not writing a shipping address at the end.

I have fixed the merge problems as well as the back issue. Let me know if something is still funky. After fixing up the merges, I couldn't reproduce the issue of the shipping address not going through, but if you could double check me or let me know if I was missing any extra steps, that would be great. 

image

**Comment by jarrilla** [comment]
Finally had time to review. Fantastic work, Jon!

**Pull request merged**
